server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_rout #路由的ID，没有固定规则但要求唯一，建议配置服务名
#          uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/payMent/getPayMentById/** #断言，路径相匹配的进行路由
        - id: payment_rout2 #路由的ID，没有固定规则但要求唯一，建议配置服务名
#          uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/discovery #断言，路径相匹配的进行路由
        - id: payment_rout3 #路由的ID，没有固定规则但要求唯一，建议配置服务名
          uri: http://localhost:8001  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/hystrix/circutBreaker/** #断言，路径相匹配的进行路由
            - After=2020-11-21T16:42:23.027+08:00[Asia/Shanghai] #设置生效时间
            - Cookie=cookieName,zzz #设置Cookie，它是一个key，Valye的键值对格式cookieName为cookie的名称，zzz为值它是java的正则表达式
            - Header=X-Request-Id, \d+ #设置请求头，它是一个key，value的键值对，请求的时候要求头带有指定的属性名称，和指定规则的Java正则表达式

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版本的，将其注册到多个注册中心