server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #使用C:\Windows\System32\drivers\etc的host配置的127.0.0.1的映射
  #    hostname: localhost #eureka服务端的服务名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone : http://eureka7002.com:7002/eureka/ #集群版本，将它注册到另外一台Eureka Server中去，相互注册相互守望
#      defaultZone : http://${eureka.instance.hostname}:${server.port}/eureka/ #设置与Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址（单机版）
  #关闭Eureka自我保护机制
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000 #心跳时间