#服务端口号
server:
  port: 8006
spring:
  application:
    name: consul-provider-payment-consul #将作为注册到consul的节点名称
# consul 注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}