server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版本的，将其注册到多个注册中心


#设置Feign客户端超时时间（OpenFeign默认支持Ribbon，由Ribbon来控制超时时间）
ribbon:
  #值的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
  # Feign日志以什么级别控制哪个接口
  com.zzz.wilson.lai.service.PaymentFeignService: debug