server:
  port: 80

spring:
  application:
    name: cloud-feign-hystrix-order-service

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版本的，将其注册到多个注册中心

feign:
 hystrix:
  enabled: true #开启feign对Hystrix的支持
#ribbon的超时时间
#ribbon:
#  ReadTimeout: 30000
#  ConnectTimeout:
ribbon:
  MaxConnectionsPerHost: 500
  MaxTotalConnections: 2000
  ConnectTimeout: 60000 #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 60000  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000